sdbs_pile/pile/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from .views import IPFSView, ExternalLinkView

app_name = 'pile'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tag/<name_or_id>', views.TagView.as_view(), name='tag'),
    path('item/<int:document_id>', views.DocumentView.as_view(), name='document'),
    path('label/<int:document_id>', views.LabelView.as_view(), name='label'),
    path('retrieve/<int:document_id>', views.DocumentWithLabelView.as_view(), name='retrieve'),
    path('image/<int:document_id>', cache_page(60 * 60 * 6)(views.BrandedImageView.as_view()), name='image'),
    path('feed', views.RecentlyUploadedFeed()),
    path('api/external_links', ExternalLinkView),
    path('api/ipfs_cids', IPFSView)
]

sdbs_pile/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sdbs_pile import settings

urlpatterns = [
    path('', include('sdbs_pile.pile.urls')),
    path('admin/', admin.site.urls),
]

if settings.STATIC_PILE:
    urlpatterns += static("/docs/", document_root=settings.BASE_DIR + "/docs")

sdbs_pile/pile/models.py
import bleach
import markdown2
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models import Count, Q
from model_utils.managers import SoftDeletableManager, SoftDeletableQuerySet
from model_utils.models import SoftDeletableModel
from ordered_model.models import OrderedModel
from pdf2image import convert_from_path

BLEACH_ALLOWED_TAGS = bleach.sanitizer.ALLOWED_TAGS + ['p', 'br', 'h1', 'h2', 'h3', 'hr']


class Tag(SoftDeletableModel):
    name = models.CharField(max_length=128, null=False, blank=False)
    description = models.TextField(null=False, blank=True)

    @property
    def html_description(self):
        return bleach.clean(bleach.linkify(markdown2.markdown(self.description)), tags=BLEACH_ALLOWED_TAGS)

    @property
    def plain_description(self):
        return bleach.clean(self.html_description, tags=[], strip=True)

    def __str__(self):
        return self.name


class DocumentQuerySet(SoftDeletableQuerySet):
    def untagged(self):
        return super().annotate(tag_count=Count('tags')).filter(tag_count=0)

    def local(self):
        return super().filter((Q(file__isnull=False) & ~Q(file='')) | Q(urls__url__contains="pile.sdbs.cz"))

    def external(self):
        return super().filter((Q(file__isnull=True) | Q(file='')) & ~Q(urls__url__contains="pile.sdbs.cz"))


class DocumentManager(SoftDeletableManager):
    _queryset_class = DocumentQuerySet


class Document(SoftDeletableModel):
    class DocumentStatus(models.TextChoices):
        REFERENCE = "REF", "Referential"
        STANDARD = "STD", "Standard"
        FRAGMENT = "FRG", "Fragment"

    class DocumentType(models.TextChoices):
        TEXT = "T", "Text"
        AUDIO = "A", "Audio"
        VIDEO = "V", "Video"
        MULTI = "+", "Multiple types"
        OTHER = "X", "Other"

    title = models.CharField(max_length=512, null=False, blank=False)
    author = models.CharField(max_length=512, null=False, blank=True)
    published = models.CharField(max_length=128, null=False, blank=True)
    description = models.TextField(max_length=2048, null=False, blank=True)
    file = models.FileField(null=True, blank=True, storage=FileSystemStorage(location='docs'))
    image = models.ImageField(null=True, blank=True, storage=FileSystemStorage(location='docs/images'))
    public = models.BooleanField(default=True, null=False, blank=False)
    media_type = models.CharField(null=False, blank=False,
                                  max_length=1, choices=DocumentType.choices, default=DocumentType.TEXT)
    status = models.CharField(null=False, blank=False,
                              max_length=3, choices=DocumentStatus.choices, default=DocumentStatus.STANDARD)
    tags = models.ManyToManyField(Tag, related_name="documents", blank=True)
    uploaded = models.DateTimeField(auto_now_add=True, null=True)
    related = models.ManyToManyField('self', related_name='related', blank=True)

    objects = DocumentManager()

    @property
    def html_description(self):
        return bleach.clean(bleach.linkify(markdown2.markdown(self.description)), tags=BLEACH_ALLOWED_TAGS)

    @property
    def plain_description(self):
        return bleach.clean(self.html_description, tags=[], strip=True)

    @property
    def url(self):
        if self.file:
            return f"/docs/{self.file.url}"
        return self.urls.first().url if self.urls.exists() else None

    @property
    def is_local_pdf(self):
        return self.file.name is not None and self.file.name.endswith(".pdf")

    @property
    def image_first_page(self):
        if self.is_local_pdf:
            images = convert_from_path(self.file.path, last_page=1)
            if images:
                return images[0]

    class Meta:
        ordering = ['-id']
        permissions = [
            ("see_hidden", "Can see hidden documents")
        ]

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('pile:document', args=[str(self.id)])

    def __str__(self):
        return f"{self.title}{f' ({self.author})' if self.author else ''}"


class DocumentLink(OrderedModel):
    document = models.ForeignKey(Document, related_name="urls", on_delete=models.CASCADE)
    url = models.URLField(null=False, blank=False)
    description = models.CharField(max_length=512, null=True, blank=True)

    order_with_respect_to = 'document'

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return f"{self.description} - {self.url}" if self.description else self.url

sdbs_pile/pile/views.py
# Create your views here.
import io
import logging
import re
from datetime import datetime
from operator import itemgetter
from random import choice

import weasyprint
from PIL import Image
from PyPDF2 import PdfFileWriter, PdfFileReader
from django.contrib.staticfiles import finders
from django.contrib.syndication.views import Feed
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import Http404, FileResponse, HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.utils.text import slugify
from django.views import View
from django.views.generic import TemplateView

from sdbs_pile import settings
from sdbs_pile.pile.models import Tag, Document, DocumentLink


class BasePileView(TemplateView):
    def get_context_data(self, **kwargs):
        tags = list(Tag.objects.all())
        tags.sort(key=lambda tag: tag.name)
        tags = [(tag, tag.documents.count()) for tag in tags]
        tags.sort(key=itemgetter(1), reverse=True)

        return {
            'tags': tags,
            'document_count': Document.objects.count(),
            'untagged_count': Document.objects.all().untagged().count(),
            'can_see_hidden': settings.STATIC_PILE or self.request.user.has_perm('pile.see_hidden'),
            'STATIC_PILE': settings.STATIC_PILE
        }


class IndexView(BasePileView):
    template_name = "front_intro.html"

    def get_context_data(self, **kwargs):
        base_context_data = super(IndexView, self).get_context_data(**kwargs)

        return {
            'recent_documents': Document.objects.order_by('-uploaded')[:10],
            'random_document': choice(Document.objects.all()[5:]) \
                if not settings.STATIC_PILE and Document.objects.count() > 0 else None,
            **base_context_data
        }


class TagView(BasePileView):
    template_name = "front_doc_listing.html"

    def get_context_data(self, name_or_id: str):
        base_context_data = super(TagView, self).get_context_data()

        if name_or_id == "*":
            tag = None
            documents = Document.objects.all()
        elif name_or_id == "_":
            tag = "UNTAGGED"
            documents = Document.objects.all().untagged()
        else:
            try:
                try:
                    tag = Tag.objects.get(id=int(name_or_id))
                except ValueError:
                    tag = Tag.objects.get(name=name_or_id)
                documents = tag.documents.all()
            except ObjectDoesNotExist:
                raise Http404

        status_documents = {s: [] for s in Document.DocumentStatus}
        for document in documents:
            status_documents[document.status] += [document]

        return {
            'tag': tag if tag != "UNTAGGED" else None,
            'untagged': tag == "UNTAGGED",
            'status_documents': status_documents,
            **base_context_data
        }


class DocumentView(BasePileView):
    template_name = "front_doc_detail.html"

    def get_context_data(self, document_id: int):
        base_context_data = super(DocumentView, self).get_context_data()

        try:
            document = Document.objects.get(pk=document_id)
        except ObjectDoesNotExist:
            raise Http404

        return {
            'document': document,
            **base_context_data
        }


class LabelView(View):
    def get(self, request: HttpRequest, document_id: int):
        try:
            document = Document.objects.get(pk=document_id)
        except ObjectDoesNotExist:
            raise Http404

        label_stream = self.get_label(request, document)
        return FileResponse(label_stream,
                            filename=f"pile_{document.id}__label__{slugify(document.title)}.pdf",
                            content_type="application/pdf")

    @staticmethod
    def get_label(request, document):
        label_html = render_to_string("label.html", {'document': document})

        stream = io.BytesIO()
        weasyprint.HTML(base_url=request.build_absolute_uri(), string=label_html).write_pdf(stream)
        stream.seek(0)
        return stream


class DocumentWithLabelView(View):
    def get(self, request: HttpRequest, document_id: int):
        try:
            document = Document.objects.get(pk=document_id)
        except ObjectDoesNotExist:
            raise Http404

        if not self.request.user.has_perm('pile.see_hidden') and not document.public and not settings.STATIC_PILE:
            raise PermissionDenied()

        if document.is_local_pdf:
            try:
                label_stream = LabelView.get_label(request, document)

                with open(document.file.path, 'rb') as document_fp:
                    writer = PdfFileWriter()
                    for reader in map(PdfFileReader, (label_stream, document_fp)):
                        for n in range(reader.getNumPages()):
                            writer.addPage(reader.getPage(n))
                    writer.addMetadata({u'/Title': f"/-\\ pile #{document.id}: {document.title}"})
                    final_stream = io.BytesIO()
                    writer.write(final_stream)

                final_stream.seek(0)
                return FileResponse(final_stream,
                                    filename=f"pile_{document.id}__label__{slugify(document.title)}.pdf",
                                    content_type="application/pdf")
            except Exception as exc:
                logging.exception(exc)

        return redirect(document.url)


class BrandedImageView(View):
    def get(self, request: HttpRequest, document_id: int):
        try:
            document = Document.objects.get(pk=document_id)
        except ObjectDoesNotExist:
            raise Http404

        margin = 32
        pile_image = Image.open(finders.find('pile_300dpi.png')).resize((256 - margin, 256 - margin))
        image = Image.open(document.image) if document.image else document.image_first_page

        result = Image.new('RGBA', (256, 256), (0, 0, 0, 0))

        if image:
            image.thumbnail((256, 256))
            result.paste(image, ((256 - image.size[0]) // 2, (256 - image.size[1]) // 2))

        result.paste(pile_image, (margin//2, margin//2), pile_image)

        if image:
            result = result.crop(result.getbbox())

        img_byte_arr = io.BytesIO()
        result.save(img_byte_arr, format='PNG')
        img_byte_arr = img_byte_arr.getvalue()

        return HttpResponse(img_byte_arr, content_type="image/png")


class RecentlyUploadedFeed(Feed):
    title = "The /-\\ pile"
    link = "https://pile.sbds.cz"
    description = "A list of most recently uploaded documents."

    def items(self):
        return Document.objects.order_by('-uploaded')[:5]

    def item_title(self, item: Document):
        return item.title

    def item_description(self, item: Document):
        return item.html_description

    def item_pubdate(self, item: Document):
        return item.uploaded or datetime.now()


def ExternalLinkView(request: HttpRequest):
    external_links = DocumentLink.objects.order_by('order', '-document_id').values_list("url", flat=True)
    external_links = [link for link in external_links if "pile.sdbs.cz" not in link]
    return HttpResponse("\n".join(external_links), content_type='text/plain')


def IPFSView(request: HttpRequest):
    ipfs_matches = [re.search(r'Qm[\w]{44}', link.url)
                    for link in DocumentLink.objects.order_by('order', '-document_id') if 'ipfs' in link.url]
    ipfs_cids = [match.group(0) for match in ipfs_matches if match]
    return HttpResponse("\n".join(ipfs_cids), content_type='text/plain')

sdbs_pile/pile/templates/front_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>The /-\ pile{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "main.css" %}">
    <link rel="icon" type="image/png" href="{% static "favicon.png" %}">
    {% block meta-og %}
        <meta property="og:title" content="The /-\ Pile"/>
        <meta property="og:type" content="website"/>
        <meta property="og:url" content="https://pile.sdbs.cz/"/>
        <meta property="og:image" content="{% static "favicon.png" %}"/>
        <meta property="og:description"
              content="This is where we upload the stuff we consider important to the larger conceptual and thematic landscape of what we do: confronting apathy, inter-subjectivity, the human right to self-determination, counter-culture and such..."/>
    {% endblock %}
    <meta property="og:site_name" content="The /-\ Pile"/>
</head>
<body>

<div id="sidebar">
    <div id="sidebar-head">
        <h1><a href="..">The /-\ pile</a></h1>
    </div>
    <div id="sidebar-taglist">
        <ul>
            <li id="sidebar-taglist-top"><a href="{% url "pile:tag" "*" %}">ALL ({{ document_count }})</a></li>
            {% if untagged_count %}
                <li id="sidebar-taglist-top"><a href="/tag/_">UNTAGGED ({{ untagged_count }})</a></li>
            {% endif %}
            {% for tag, tag_count in tags %}
                {% if tag_count > 0 %}
                    <li><a href="{% url 'pile:tag' tag.id %}">{{ tag.name }} ({{ tag_count }})</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>

<div id="content">
    {% block content %}{% endblock %}
</div>

{% if not STATIC_PILE %}
    <div id="login">
        <a href="/admin">[login // maintain]</a>
    </div>
{% endif %}

<script>
    (function () {
        window.counter = 'https://sdbs_pile.goatcounter.com/count';

        var script = document.createElement('script');
        script.async = 1;
        script.src = '//gc.zgo.at/count.js';
        var ins = document.getElementsByTagName('script')[0];
        ins.parentNode.insertBefore(script, ins);
    })();
</script>
</body>
</html>

sdbs_pile/pile/templates/front_doc_detail.html
{% extends "front_base.html" %}

{% block title %} | #{{document.id}}: {{ document.title }}{% endblock %}

{% block content %}
    <div class="text document" vocab="https://schema.org/" typeof="CreativeWork" resource="{% url "pile:document" document.id %}">
        <h1 property="name">{{ document.title }}</h1>

        {% if document.author %}
            <h2 property="author">{{ document.author }}</h2>
        {% endif %}

        {% if document.published %}
            <h3>Published: <span property="datePublished">{{ document.published }}</span></h3>
        {% endif %}

        <h3>Type: {{ document.get_media_type_display }}</h3>

        {% if document.tags.count > 0 %}
            <h3 class="doc-taglist">
                <span>Tags: </span>
                {% for tag in document.tags.all %}
                    <li>
                        <a href="{% url "pile:tag" tag.id %}" title="{{ tag.description }}">
                            {{ tag.name }}
                        </a>
                    </li>
                {% endfor %}
            </h3>
        {% endif %}

        {% if document.description %}
            <div class="doc-description">
                <span class="doc-description-intro">
                    {% if document.url %}Description{% else %}Content{% endif %}:
                </span>
                <div property="description"> {{ document.html_description | safe }} </div>
            </div>
        {% endif %}

        {% if document.public or can_see_hidden %}
            {% if document.is_local_pdf %}
                <div class="doc-link">
                    <span class="doc-link-intro">Access file as:</span>
                    <a property="url" href="{% url "pile:retrieve" document.id %}">
                        Entry #{{ document.id }} of /-\ pile
                    </a>
                </div>

                <div class="doc-link">
                    <span class="doc-link-intro">Get original document at: </span>
                    <a href="{{ document.url }}">{{ document.url }}</a>
                </div>

                {% if document.urls.count > 0 %}
                    <div class="doc-link-intro">Also see:</div>
                    {% for link in document.urls.all %}
                        <div class="doc-link doc-link-plus">
                            <a href="{{ link.url }}">{{ link.description|default:link.url }}</a>
                        </div>
                    {% endfor %}
                {% endif %}
            {% else %}
                <div class="doc-link">
                    <span class="doc-link-intro">Access file at:</span>
                    <a property="url" href="{{ document.url }}">{{ document.url }}</a>
                </div>

                <div class="doc-link">
                    <span class="doc-link-intro">Get label for file at:</span>
                    <a href="{% url "pile:label" document.id %}">{% url "pile:label" document.id %}</a>
                </div>
                
                {% if document.urls.count > 1 %}
                    <div class="doc-link-intro">Also see:</div>
                    {% for link in document.urls.all|slice:"1:" %}
                        <div class="doc-link doc-link-plus">
                            <a href="{{ link.url }}">{{ link.description|default:link.url }}</a>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        {% else %}
            <div class="doc-link">
                <span class="doc-link-intro">Get label for file at:</span>
                <a href="{% url "pile:label" document.id %}">{% url "pile:label" document.id %}</a>
            </div>

            {% if document.urls.count > 0 %}
                <div class="doc-link-intro">Related URLs:</div>
                {% for link in document.urls.all %}
                    <div class="doc-link doc-link-plus">
                        <a href="{{ link.url }}">{{ link.description|default:link.url }}</a>
                    </div>
                {% endfor %}
            {% endif %}
        {% endif %}
        {% if document.related.exists %}
            <hr>
            <h2>Related documents</h2>
            <ul>
                {% for related in document.related.all %}
                    <li>
                        <a href="{% url 'pile:document' related.id %}">
                            {% if related.uploaded %}
                                <em>({{ related.uploaded|date:"Y/m/d G:i:s" }})</em>
                            {% endif %}
                            {{ related.title }}

                            <div class="short-doc-desc">
                                {{ related.plain_description }}
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

{% block meta-og %}
    <meta property="og:title" content="#{{document.id}}: {{ document.title }}"/>
    <meta property="og:url" content="https://pile.sdbs.cz{% url "pile:document" document.id %}"/>
    <meta property="og:description" content="{{ document.plain_description }}"/>
    <meta property="og:type" content="article"/>
    <meta property="og:image" content="{% url "pile:image" document.id %}"/>
{% endblock %}

sdbs_pile/pile/templates/front_doc_listing.html
{% extends "front_base.html" %}
{% load static %}

{% block title %}
{% spaceless %}
    {% if tag %}
        | Filed under "{{ tag.name }}"
    {% elif untagged %}
        | Untagged
    {% else %}
        | All documents
    {% endif %}
{% endspaceless %}
{% endblock %}

{% block content %}
    {% if tag %}
        <div class="text tag-text">
            <h1>{{ tag.name }}</h1>
            <div class="tag-desc">{{ tag.html_description|safe }}</div>
        </div>
    {% endif %}

    {% for status, documents in status_documents.items %}
        {% if documents|length > 0 %}
            <div class="text docs-header"><h3>{{ status.label }}</h3></div>
            {% for document in documents %}
                <div class="text doc-item">
                    {% if document.public or can_see_hidden %}
                        <a class="doc-item-link" href="{% url "pile:retrieve" document.id %}">🔗</a>
                    {% endif %}
                    <a href="{% url "pile:document" document.id %}">
                        <div class="doc-item-text">
                            <h2>{{ document.title }}</h2>
                            <h3>{{ document.author }} {{ document.published }}</h3>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block meta-og %}
    {% if tag %}
        <meta property="og:title" content="Documents under &quot;{{ tag.name }}&quot;"/>
        <meta property="og:url" content="https://pile.sdbs.cz{% url "pile:tag" tag.id %}"/>
        <meta property="og:description" content="{{ tag.description }}"/>
        <meta property="og:type" content="website"/>
        <meta property="og:image" content="{% static "favicon.png" %}"/>
    {% endif %}
{% endblock %}

sdbs_pile/pile/templates/front_intro.html
{% extends "front_base.html" %}

{% block content %}
    <div class="text">
        <p class="intro"> This site is the sdbs pile, where we upload the stuff we consider important to the larger
            conceptual and thematic landscape of what we do: "confronting apathy", inter-subjectivity, the human right
            to
            self-determination, counter-culture and such...</p>
        <p class="intro czech">Tohle je hromádka zajímavýho materiálu co něco znamená v kontextu sdbs - budeme sem
            postupně dávat ty nejdůležitější nebo nejzajímavější věci, zatim se o tom ale nikde moc nešiřte.</p>
        <p class="intro sign">/-\</p>
    </div>
    {% if random_document %}
        <div class="text">
            <h2>Random document</h2>
            <div class="random-document">
                <a href="{% url 'pile:document' random_document.id %}">
                    <span>#{{ random_document.id }}: {{ random_document.title }}</span>

                    <div class="short-doc-desc">
                        {% if random_document.tags.count > 0 %}
                            <div class="random-tags">Filed under: {{ random_document.tags.all | join:" / " }}</div>
                        {% endif %}
                    </div>
                    <div class="short-doc-desc">
                        {{ random_document.plain_description }}
                    </div>
                </a>
            </div>
        </div>
    {% endif %}

    <div class="text recent-additions">
        <h2>Recent additions</h2>
        <ul>
            {% for document in recent_documents %}
                <li>
                    <a href="{% url 'pile:document' document.id %}">
                        {% if document.uploaded %}
                            <em>({{ document.uploaded|date:"Y/m/d G:i:s" }})</em>
                        {% endif %}
                        {{ document.title }}

                        <div class="short-doc-desc">
                            {{ document.plain_description }}
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

sdbs_pile/pile/templates/label.html
{% load static %}

<head>
    <title>LABEL FOR "{{ document.title }}"</title>
    <!--suppress CssNoGenericFontName -->
    <style>
        body {
            font-family: prociono;
            font-size: 14px;
        }

        h1, h2, h3 {
            margin: 0;
            padding: 0;
            bookmark-level: none;
        }

        h1, h2 {
            font-size: 24px;
        }

        a {
            color: black;
            text-decoration: none;
        }

        .exlibris {
            text-align: center;
            margin-bottom: 10px;
        }

        .label-outer {
            width: 100%;
            border: 5px solid black;
            padding: 10px;
        }

        .label-column {
            float: left;
        }

        .label-stamp-outer {
            width: 20%;
        }

        .label-stamp {
            width: 100%;
            border: 2px solid black;
        }

        #pile-logo {
            width: 80%;
            padding: 10px 10%;
        }

        .label-stamp-subtitle {
            text-align: center;
            width: 100%;
            margin-bottom: 5px;
            font-size: 20px;

            margin-top: -12px; /* prociono specific */
        }

        .label-text {
            float: right;
            width: 77.5%;
        }

        .label-title {
            margin: 0;
            padding: 0;
        }

        .label-otherinfo {
            font-size: 14px;
        }

        .label-description {
            text-align: justify;
            margin-top: 0;
            padding-top: 0;
        }


        .label-footer {
            width: 100%;
            text-align: right;
            clear: both;
        }

        .absolute-footer {
            width: 100%;
            position: absolute;
            text-align: center;
            bottom: 0;
            left: 0;
        }
    </style>
</head>
<body>
<h1 class="exlibris">ex libris /-\ pile</h1>
<div class="label-outer">
    <div class="label-upper">
        <div class="label-stamp-outer">
            <div class="label-column label-stamp">
                <img id="pile-logo" src="{% static "pile_black.svg" %}" alt="/-\ Pile"/>
                <div class="label-stamp-subtitle">#{{ document.id|stringformat:"04d" }}</div>
            </div>
        </div>
        <div class="label-column label-text">
            <h2 class="label-title">{{ document.title }}</h2>
            <h3 class="label-otherinfo">
                {% if document.author %}
                    By {{ document.author }}
                {% endif %}
                {% if document.published %}
                    <div class="label-otherinfo-date">(Published: {{ document.published }})</div>
                {% endif %}
            </h3>
            <p class="label-description">{{ document.html_description | safe }}</p>
        </div>
    </div>
    <div class="label-footer">
        {% if document.tags.count > 0 %}
            <div class="label-footer-tags">Filed under:
            {% for tag in document.tags.all %}
                {{ tag.name }}{% if not forloop.last %} / {% endif %}
            {% endfor %}
        {% endif %}
        <div class="label-footer-url">
            Available at:
            <a href="https://pile.sdbs.cz/item/{{ document.id }}">https://pile.sdbs.cz/item/{{ document.id }}</a>
        </div>
        </div>
    </div>
    <div class="absolute-footer">
        read or share
    </div>
</body>